hieukun1011/vtc_elearning

addons_common/restful/controllers/all_course.py
addons_common/restful/controllers/get_course_by_id.py
addons_common/restful/controllers/get_lesson_by_id.py
addons_common/restful/controllers/main.py

api fix bug

---

addons_common/restful/__manifest__.py
addons_common/restful/controllers/elearning.py
addons_common/restful/controllers/employee.py
addons_common/restful/controllers/get_course_by_id.py
addons_common/restful/controllers/get_lesson_by_id.py
addons_common/restful/controllers/main.py
addons_common/restful/controllers/project.py
addons_common/restful/controllers/recruitment.py
addons_common/restful/models/__init__.py
addons_common/restful/models/access_token.py
addons_common/restful/models/slide_slide.py
addons_common/restful/views/slide_slide.xml
addons_elearning/vct_elearning_upload/models/upload_file.py
addons_elearning/vtc_elearning/models/quiz.py
odoo/addons/base/models/ir_attachment.py
odoo/cli/deploy.py
odoo/cli/scaffold.py

Feature wp minhduc

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/views/slide_channel_inherit.xml

toi-uu-dashboard

---

addons_common/restful/controllers/all_course.py
addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/views/slide_channel_inherit.xml

fix-api-all-course-and-fix-level-course

---

addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/views/slide_channel_inherit.xml

add-price-course

---

addons_common/restful/controllers/all_course.py
addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/views/slide_channel_inherit.xml

add-special-course

---

addons_common/restful/controllers/get_course_by_id.py

changed data attachment api /api/get/course_by_id

---

addons_elearning/vtc_elearning/models/res_user.py

detele-fields

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/views/comment_view_inherit.xml
addons_elearning/vtc_elearning/views/lecturers_view.xml
addons_elearning/vtc_elearning/views/rating_system.xml
addons_elearning/vtc_elearning/views/slide_channel_inherit.xml
addons_elearning/vtc_elearning/views/student_view.xml

toi-uu-odoo

---

addons_elearning/vtc_elearning/views/rating_system.xml

toi-uu-odoo-3

---

addons_common/restful/controllers/get_course_by_id.py

fix-api-get-course-by-id

---

addons_common/restful/controllers/all_course.py

fix-api-all-course

---

addons_common/restful/controllers/get_course_by_id.py
addons_common/restful/controllers/get_lesson_by_id.py

fix-timeout

---

addons_elearning/vtc_elearning/views/rating_system.xml

add-time-rating-system

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/views/rating_system.xml

add-time-rating-system: update part2

---

addons_common/restful/controllers/get_course_by_id.py
addons_common/restful/controllers/user.py

get-id-avt

---

addons_common/restful/controllers/get_course_by_id.py

reformat-star

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/rating_system.py
addons_elearning/vtc_elearning/views/rating_system.xml

changed-text-rating-system

---

addons_elearning/vtc_elearning/i18n/vi_VN.po

translation-text-odoo

---

addons_common/restful/controllers/get_lesson_by_id.py
addons_common/restful/controllers/user.py

fix-api-from-hoangdacdo

---

addons_common/restful/controllers/user.py

fix-mail-server

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/rating_system.py

sua text danh gia he thong

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/views/student_view.xml

phan-quyen-tai-khoan

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/rating_system.py

fix-dashboard

---

addons_elearning/vtc_elearning/i18n/vi_VN.po

fix-dashboard: update p2

---

addons_common/restful/controllers/all_course.py
addons_common/restful/controllers/get_course_by_id.py
addons_common/restful/controllers/sign_student.py
addons_common/restful/controllers/user.py
addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/models/student.py

Feature wp import data

---

addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/views/slide_slide_view_inherit.xml

add-type-video-in-slide

---

addons_common/restful/controllers/quiz.py

add-id-quiz

---

addons_common/restful/controllers/get_lesson_by_id.py
addons_elearning/vtc_elearning/i18n/vi_VN.po
addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/views/slide_slide_view_inherit.xml

Add type video in slide

---

addons_common/restful/controllers/get_course_by_id.py

Minhduc add id quiz 26 9

---

addons_common/restful/controllers/get_course_by_id.py

remove-case-if-uid

---

addons_common/restful/controllers/get_course_by_id.py

get-tag-cource

---

addons_common/restful/controllers/main.py
addons_common/restful/controllers/quiz.py
addons_elearning/vtc_elearning/models/slide_slide.py

fix-duplicate

---

addons_elearning/vtc_elearning/models/slide_slide.py
addons_elearning/vtc_elearning/views/slide_slide_view_inherit.xml

tối ưu thêm nội dung khoá học

---

addons_elearning/vtc_elearning/models/student.py

bắt điều kiện quận/huyện xã/phường theo tỉnh/TP

---

addons_elearning/vtc_elearning/models/student.py

onchange tỉnh/tp, quận/huyện, phường xã

---

addons_common/restful/controllers/all_course.py

fix-type-cource

---

addons_common/restful/controllers/get_course_by_id.py

fix-process

---

addons_common/restful/controllers/get_course_by_id.py
addons_elearning/vtc_elearning/models/student.py

contrain-field

---

addons_common/restful/controllers/get_lesson_by_id.py
addons_common/restful/controllers/student_infor.py
addons_elearning/vtc_elearning/models/student.py

contrains-case

---

addons_elearning/vtc_elearning/views/product_template.xml

file product template xml

---

addons_elearning/vtc_elearning/models/student.py

fix bug o model student.student

---

addons_elearning/vtc_elearning/models/student.py

fix-public-user
